slow player down while holding loaded rocket
MT-CTF/shooter pull request #4
Opened 2021-04-20 14:33 UTC by olliy1or

2021-04-20 14:35 UTC, olliy1or commented
this could close https://github.com/MT-CTF/capturetheflag/issues/562 ??

2021-04-20 14:48 UTC, LoneWolfHT requested changes

2021-04-20 14:48 UTC, LoneWolfHT commented on shooter_rocket/init.lua
> +    if timer >= 0.1 then
The interval could be `1` or something similar. A second-long delay (at most in this case) isn't much. And we can just ignore the cases where the player loads and fires immediately after

2021-04-20 14:48 UTC, LoneWolfHT commented on shooter_rocket/init.lua
> +                timer = 0
This should be moved beneath `if timer >= 0.1 then`

2021-04-20 14:48 UTC, LoneWolfHT commented on shooter_rocket/init.lua
> +                })
Might want to use the physics mod for this, if it can be found by shooter. Otherwise it might conflict with other mods

2021-04-21 02:02 UTC, olliy1or commented on shooter_rocket/init.lua
> +    if timer >= 0.1 then
done.

2021-04-21 02:03 UTC, olliy1or commented on shooter_rocket/init.lua
> +                timer = 0
done.

2021-04-21 02:03 UTC, olliy1or commented on shooter_rocket/init.lua
> +                })
And done.

2021-04-22 00:22 UTC, Panquesito7 commented on shooter_rocket/init.lua
> +	plcooldown[player:get_player_name()] = 0
Maybe the cooldown should be saved in the player's meta or something like that. I could simply leave, join, take the rocket, and shoot again.

2021-04-22 00:22 UTC, Panquesito7 commented on shooter_rocket/init.lua
> +			if not minetest.setting_getbool("creative_mode") then
The method you're using is deprecated. Use this one instead.
```suggestion
			if not minetest.settings:get_bool("creative_mode") then
```

2021-04-22 00:24 UTC, olliy1or commented on shooter_rocket/init.lua
> +	plcooldown[player:get_player_name()] = 0
Don't think people would leave and join just so they can shoot a rocket, also by the time they could leave and join the timer would most likely be up

2021-04-22 00:41 UTC, Panquesito7 requested changes

2021-04-22 00:41 UTC, Panquesito7 commented on shooter_rocket/init.lua
> +		hud_event.new(user:get_player_name(), {
`hud_event` should be added in `shooter_rocket`'s dependencies.

2021-04-22 00:49 UTC, olliy1or commented on shooter_rocket/init.lua
> +	plcooldown[player:get_player_name()] = 0
done think ppl will rejoin to bypass a 5sec cooldown

2021-04-22 00:50 UTC, Panquesito7 approved these changes

2021-04-22 14:56 UTC, LoneWolfHT commented on shooter_rocket/init.lua
> +end)
Could remove this and apply my other suggestions

2021-04-22 14:56 UTC, LoneWolfHT commented on shooter_rocket/init.lua
> +		if plcooldown[user:get_player_name()] ~= 0 then
```lua
if plcooldown[user:get_player_name()] then
```

2021-04-22 14:56 UTC, LoneWolfHT commented on shooter_rocket/init.lua
> +			local yaw = user:get_look_horizontal()
Should add
```lua
local username = user:get_player_name()
```

You could then change all the following code that calls user:get_player_name()

2021-04-22 14:57 UTC, LoneWolfHT commented on shooter_rocket/init.lua
> +					plcooldown[user:get_player_name()] = 0
Can just set this to nil if the previous suggestions are implemented

2021-04-22 16:22 UTC, olliy1or commented on shooter_rocket/init.lua
> +		if plcooldown[user:get_player_name()] ~= 0 then
Done :heavy_check_mark:

2021-04-22 16:23 UTC, olliy1or commented on shooter_rocket/init.lua
> +			local yaw = user:get_look_horizontal()
Done :heavy_check_mark:

2021-12-01 18:58 UTC, closed without merging